services:
  redis:
    image: redis:8.0-M02-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0.3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
