app = "workflow-manager-rabbit"
primary_region = "mia"
kill_timeout = 10

build.image = "docker.io/rabbitmq:4.0.3-management"

[env]

# rabbitmq main
[[services]]
internal_port = 5672
protocol = "tcp"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "60s"

# rabbitmq admin
[[services]]
internal_port = 15672
protocol = "tcp"

[[services.ports]]
handlers = ["tls", "http"]
port = "15672"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "60s"

[[vm]]
size = "shared-cpu-1x"
memory = "1gb"
cpus = 1
cpu_kind = "shared"
processes = ["app"]
