load("//:build-tools/rules/ts/vite.bzl", "vite_ts_project")

vite_ts_project(
    name = "new-workflow-form",
    srcs = ["new-workflow-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "authentication-context",
    srcs = ["authentication-context.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "authentication-display",
    srcs = ["authentication-display.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/mobx-react-lite",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "new-state-form",
    srcs = ["new-state-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "new-entity-form",
    srcs = ["new-entity-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/components:form-submitter",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "set-config-form",
    srcs = ["set-config-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager:node_modules/mobx-react-lite",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "attributes-form",
    srcs = ["attributes-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager:node_modules/decimal.js",
        "//webapps/workflow_manager:node_modules/dayjs",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/components:form-submitter",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "state-change-options",
    srcs = ["state-change-options.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager:node_modules/decimal.js",
        "//webapps/workflow_manager:node_modules/dayjs",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)

vite_ts_project(
    name = "change-state-rules-form",
    srcs = ["change-state-rules-form.tsx"],
    declaration = True,
    resolve_json_module = True,
    transpiler = "tsc",
    tsconfig = "//webapps/workflow_manager:tsconfig",
    visibility = ["//webapps/workflow_manager:__subpackages__"],
    deps = [
        "//webapps/workflow_manager:node_modules/@types/react",
        "//webapps/workflow_manager:node_modules/@types/react-dom",
        "//webapps/workflow_manager:node_modules/react",
        "//webapps/workflow_manager:node_modules/react-hook-form",
        "//webapps/workflow_manager:node_modules/@hookform/resolvers",
        "//webapps/workflow_manager:node_modules/zod",
        "//webapps/workflow_manager:node_modules/decimal.js",
        "//webapps/workflow_manager:node_modules/dayjs",
        "//webapps/workflow_manager/src/components/ui",
        "//webapps/workflow_manager/src/lib:utils",
        "//webapps/workflow_manager/src/store:workflow-store",
    ]
)
